runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  STORAGE_DIR: /tmp
  APP_KEY: 'base64:KxqmLrjEh07kBMkS4ThoHS4V6dnpe5asSsIxSD0UouE='
  APP_NAME: Legal-Ally
  APP_DEBUG: true
  APP_LOG_LEVEL: debug
  MYSQL_DSN: mysql:unix_socket=/cloudsql/legalally;dbname=legalally
  MYSQL_USER: legalally
  MYSQL_PASSWORD: 'taxicab1729'