runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  STORAGE_DIR: /tmp
  APP_KEY: 'base64:KxqmLrjEh07kBMkS4ThoHS4V6dnpe5asSsIxSD0UouE='
  APP_NAME: Legal-Ally
  APP_DEBUG: true
  APP_LOG_LEVEL: debug
  MAILGUN_DOMAIN: sandbox5e57686f219a41b0907c78529014f628.mailgun.org
  MAILGUN_SECRET: key-3b79bed7bc40cd8ac6ac4f1e7b821518
  MAIL_DRIVER: mailgun
  DB_HOST: 35.200.211.43
  DB_DATABASE: legalally
  DB_USERNAME: legalally
  DB_PASSWORD: 'taxicab1729'
  DB_SOCKET: '/cloudsql/shining-booth-185110:asia-south1:legalally'