runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: rlfsn8Jpu/2aFqXJXHUzqYS67n6zamjqjy6pr7VxwaU=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  ## Set these environment variables according to your CloudSQL configuration.

beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
	DB_CONNECTION:mysql
	DB_HOST:127.0.0.1
	DB_PORT:3306
	DB_DATABASE:homestead
	DB_USERNAME:homestead
	DB_PASSWORD:secret